create external table if not exists ods_mysql.ods_beeper2_drivers_driver_invitation (
    `id` bigint comment "主键" ,
    `invitee_driver_id` bigint comment "被邀请司机id" ,
    `invitee_car_type` bigint comment "被邀请司机车型" ,
    `invitee_car_num` string comment "被邀请司机车牌号" ,
    `invitee_city_id` bigint comment "被邀请司机城市id" ,
    `invitee_district_id` bigint comment "被邀请司机区县id" ,
    `invitee_adcid` bigint comment "被邀请司机管理区id" ,
    `invitee_created_at` timestamp comment "被邀请司机注册时间" ,
    `inviter_driver_id` bigint comment "邀请人司机id" ,
    `inviter_mobile` string comment "邀请人司机手机号" ,
    `inviter_adcid` bigint comment "邀请人司机管理区id" ,
    `is_info_complete` int comment "被邀请司机资料是否完整" ,
    `is_identity_approved` int comment "被邀请司机是否通过身份认证" ,
    `is_car_approved` int comment "被邀请司机是否通过车辆认证" ,
    `is_bones_paid` int comment "邀请奖励是否已打款" ,
    `bones_paid_at` timestamp comment "邀请奖励打款时间" ,
    `created_at` timestamp comment "创建时间" ,
    `updated_at` timestamp comment "更新时间" )
 stored as orc