create external table if not exists ods.ods_trans_driver_bid (
    `id`  bigint comment "司机竞价id" ,
    `trans_task_id`  bigint comment "任务id" ,
    `driver_id`  bigint comment "司机id" ,
    `status`  int comment "司机竞价的状态" ,
    `dprice`  bigint comment "司机竞价的价格（单天价格，单位：分）" ,
    `slogan`  string comment "司机竞标语" ,
    `modify_count`  bigint comment "报价被修改的次数" ,
    `comment`  string comment "对竞价状态变更的简要说明" ,
    `created_at`  timestamp comment "创建时间" ,
    `updated_at`  timestamp comment "最后更新时间" ,
    `dd_id`  bigint comment "拓展经理id" ,
    `is_first_onboard`  int comment "是否是首岗报价（只有拥有首岗奖费率的竞价在被选中的时候，且该司机没有过起他任何首岗竞价，才会被设置为1）" ,
    `first_onboard_rate`  double comment "首岗奖费率 例如: 0.20 (20%)" ,
    `car_team_mgr_id`  bigint comment "提交报价的车队长id" ,
    `is_ignore_restrict`  int comment "限行是否可以配送" ,
    `car_id`  bigint comment "司机的车型ID" ,
    `car_num`  string comment "司机的车牌号码" ,
    `car_team_id`  bigint comment "司机所属车队id" ,
    `end_date`  timestamp comment "因司机违约或无责任解约等竞价结束时间" ,
    `insurance_type`  int comment "司机保险类型" ,
    `insurance_begun_at`  timestamp comment "保障开始日期" ,
    `select_driver_time`  timestamp comment "选中司机时间" )
 stored as orc