create external table if not exists ods_mysql.ods_beeper_trans_task__trans_task_requirement (
    `trans_task_id` bigint comment "任务ID" ,
    `city_id` string comment "城市ID(json array)" ,
    `car_type_id` string comment "车型ID(json array)" ,
    `deliver_experience` string comment "配送经验（多选+详情）" ,
    `handling_type` int comment "搬运程度" ,
    `other_handling_req` string comment "其他搬运说明" ,
    `is_req_xiaogong` int comment "是否需要司机自带小工" ,
    `is_with_load` int comment "是否有人帮忙装货" ,
    `is_with_unload` int comment "是否有人帮忙卸货" ,
    `is_with_board` int comment "是否带尾板" ,
    `is_need_clear_seats` int comment "是否需要拆后座" ,
    `is_need_tuiche` int comment "是否需要推车" ,
    `is_limit_phone` int comment "是否安卓系统手机、3G以上网络" ,
    `is_need_double_fire_extinguisher` int comment "是否需要配备双灭火器" ,
    `is_need_lock` int comment "是否需要配备明锁/暗锁" ,
    `is_ignore_restrict` int comment "限行是否要求配送" ,
    `is_need_practice_before_onboard` int comment "是否需要上岗前实习" ,
    `driver_req` string comment "其他上岗要求" ,
    `other_desc` string comment "补充说明" ,
    `extra` string comment "其它信息(json)" ,
    `created_at` timestamp comment "创建时间" ,
    `updated_at` timestamp comment "最后更新时间" ) partitioned by(p_day string)
 stored as orc