create external table if not exists ods_mysql.ods_beeper_trans_task__trans_task_vas_customer_insurance (
    `id` bigint comment "自增id" ,
    `trans_task_id` bigint comment "任务id" ,
    `customer_id` bigint comment "客户id" ,
    `insurance_type` int comment "保险类型(100中货值保险,200高货值保险)" ,
    `charge_type` int comment "保险价位类别(3万/5万/10万/200万)" ,
    `insure_way` int comment "保险购买方式(100合约购买,200线路购买)" ,
    `sum_insured` bigint comment "最高保额,单位:分" ,
    `customer_price_mode` int comment "客户保费价格计算类型：100 按比率计算；200 按固定金额计算" ,
    `customer_mode_number` double comment "计算客户保费参照的比率或固定金额" ,
    `min_customer_price` bigint comment "客户保费的最小值(单位:分)" ,
    `yn_price_mode` int comment "云鸟给保险公司支付的费用计算类型：100 按比率计算；200 按固定金额计算" ,
    `yn_mode_number` double comment "云鸟给保险公司支付的费用参照的比率或固定金额" ,
    `is_enable` int comment "1可用,0不可用" ,
    `have_customer_insurance` int comment "是否购买了客户保价,1已购买,0没有购买" ,
    `operator_id` bigint comment "操作人ID" ,
    `source` int comment "操作来源" ,
    `created_at` timestamp comment "创建时间" ,
    `updated_at` timestamp comment "最后更新时间" ) partitioned by(p_day string)
 stored as orc