create external table if not exists ods_mysql.ods_beeper_trans_task__trans_task (
    `id` bigint comment "任务ID" ,
    `version` int comment "任务版本号" ,
    `customer_id` bigint comment "客户ID" ,
    `warehouse_id` bigint comment "仓库ID" ,
    `line_name` string comment "线路名称" ,
    `type` int comment "任务类型" ,
    `status` int comment "任务状态" ,
    `substatus` int comment "任务子状态" ,
    `open_task_time` timestamp comment "开启任务的时间（开标时间）" ,
    `driver_id` bigint comment "司机ID" ,
    `customer_price` bigint comment "客户价格, 单位:人民币分" ,
    `driver_price` bigint comment "司机价格, 单位:人民币分" ,
    `driver_info` string comment "司机信息(json)" ,
    `schedule` string comment "符合RFC2445标准的重复事件字符串表达式" ,
    `work_begin_time` string comment "上班时间（到仓时间）" ,
    `time_cost` bigint comment "预计工作耗时(秒)" ,
    `onboard_date` date comment "上岗日期" ,
    `end_date` date comment "任务结束日期" ,
    `expected_end_date` date comment "预计任务结束日期" ,
    `is_distribution_point_fixed` int comment "配送点是否固定" ,
    `distribution_point_min` int comment "预计配送点最小个数" ,
    `distribution_point_max` int comment "预计配送点最大个数" ,
    `distribution_area` string comment "配送区域描述(配送点固定时为备注)" ,
    `distance_min` double comment "配送里程最小值" ,
    `distance_max` double comment "配送里程最大值" ,
    `is_back` int comment "是否要求返仓" ,
    `is_ignore_restrict` int comment "限行是否要求配送" ,
    `is_need_receipt` int comment "是否需要回单" ,
    `receipt_type` int comment "回单方式" ,
    `receipt_info` string comment "回单信息(json)" ,
    `expected_price_min` bigint comment "客户预期单趟价格最小值（单位：分）" ,
    `expected_price_max` bigint comment "客户预期单趟价格最大值（单位：分）" ,
    `expected_price_describe` string comment "影响司机报价的情况说明" ,
    `reason` string comment "招标原因（单选+其他）" ,
    `driver_welfare` string comment "司机福利、补贴及奖励(json)" ,
    `comment` string comment "更新线路任务为废弃, 等终点状态的说明" ,
    `cargo_type` string comment "货物类型" ,
    `cargo_volume_min` double comment "货物体积最小值，单位：立方米" ,
    `cargo_volume_max` double comment "货物体积最大值，单位：立方米" ,
    `cargo_weight_min` double comment "货物重量最小值，单位：吨" ,
    `cargo_weight_max` double comment "货物重量最大值，单位：吨" ,
    `cargo_number_min` int comment "货物件数最小值，单位：个|件|箱|捆" ,
    `cargo_number_max` int comment "货物件数最大值，单位：个|件|箱|捆" ,
    `created_at` timestamp comment "任务创建时间" ,
    `updated_at` timestamp comment "最后更新时间" ,
    `deleted_at` timestamp comment "删除时间" ) partitioned by(p_day string)
 stored as orc