create external table if not exists ods_mysql.ods_beeper_customer_customer_account (
    `id` bigint comment "记录id" ,
    `customer_id` bigint comment "客户id" ,
    `service_telephone` string comment "客户客服电话" ,
    `company_name` string comment "公司全称" ,
    `company_id` bigint comment "公司id" ,
    `post_addr` string comment "收件地址" ,
    `post_code` string comment "邮政编码" ,
    `bank` bigint comment "银行id" ,
    `bank_account_name` string comment "账户名称" ,
    `bank_account_num` string comment "银行账号" ,
    `tcpp` double comment "客户运力利润率" ,
    `spp` double comment "客户服务费率" ,
    `business_license` string comment "营业执照号" ,
    `business_license_image` string comment "营业执照扫描件" ,
    `opening_license_image` string comment "开户许可证件照片" ,
    `pay_bank` bigint comment "付款账号银行id" ,
    `pay_bank_account_name` string comment "付款账号账户名称" ,
    `pay_bank_account_num` string comment "付款账号银行账号" ,
    `realname_approve_userid` bigint comment "实名认证操作人id" ,
    `realname_approve_time` timestamp comment "实名认证时间" ,
    `created_at` timestamp comment "创建时间" ,
    `updated_at` timestamp comment "最后更新时间" )
 stored as orc