create external table if not exists ods_mysql.ods_beeper_trans_event__yn_trans_event (
    `id` bigint comment "事件id，即出车计划ID" ,
    `trans_task_id` bigint comment "线路任务ID" ,
    `customer_id` bigint comment "客户ID" ,
    `customer_price` bigint comment "客户价格，单位：分" ,
    `warehouse_id` bigint comment "仓库ID" ,
    `driver_id` bigint comment "司机ID" ,
    `driver_price` bigint comment "司机价格，单位:分" ,
    `sales_id` bigint comment "客服经理ID" ,
    `sop_mgr_id` bigint comment "现控经理id" ,
    `bid_mgr_id` bigint comment "岗位管理经理ID" ,
    `dd_id` bigint comment "拓展经理ID" ,
    `car_id` bigint comment "司机的车型ID" ,
    `car_num` string comment "司机的车牌号码" ,
    `car_team_id` bigint comment "司机所属车队id" ,
    `status` int comment "状态" ,
    `type` int comment "运力类型，默认为普通运力" ,
    `inspect_status` int comment "检察状态" ,
    `inspect_at` timestamp comment "检察状态最后更新时间" ,
    `comment` string comment "状态变化的描述：例如旷工原因、请假原因" ,
    `work_time` timestamp comment "出车日期 到仓时间" ,
    `work_begin_time` string comment "到仓时间" ,
    `time_cost` bigint comment "预计花费时间 单位：秒" ,
    `created_at` timestamp comment "任务创建时间" ,
    `updated_at` timestamp comment "最后更新时间" ,
    `is_del` int comment "出车计划是否被删除" ,
    `fcc_id` bigint comment "现控员ID" ,
    `invoice_contents` string comment "存储当时需开发票的内容" ,
    `task_type` int comment "线路任务类型" ,
    `task_line_name` string comment "任务线路名称" ,
    `task_is_back` int comment "是否返仓 0不要求；1要求" ,
    `is_addition` int comment "该出车记录是否是加跑" ,
    `addition_count` bigint comment "加跑次数，表示该出车记录被加跑了几次" ,
    `addition_comment` string comment "加跑说明，该出车记录被设置加跑的时候的说明文字" ,
    `addition_seq` bigint comment "当该出车记录为加跑记录的时候，表示该加跑是第几次加跑，序号" ,
    `source_event_id` bigint comment "当该出车记录为加跑记录的时候，记录其父项出车计划ID 即是对那一条出车计划进行加跑" ,
    `first_pay_money` int comment "是否首次签到，用来做首日打款用的，一个司机只能有一个" ,
    `first_check_in` int comment "是否首次签到，用来做产生待评价用的，一个司机在一个客户的一个仓库下只能有一个" ,
    `is_supplement` int comment "是否为补签到" ,
    `is_late` int comment "是否迟到" ,
    `is_wrong_location` int comment "是否签到位置与仓位置偏差大于1.5公里" ,
    `adc_id` bigint comment "客户所属管理区ID" ,
    `complete_time` timestamp comment "运力完成时间" ,
    `project_type` int comment "客户项目类型" ,
    `bu_leader_id` bigint comment "客户所属bu leader的id" ,
    `new_trade_level_one` bigint comment "客户新行业一级分类id'" ,
    `new_trade_level_two` string comment "客户新行业二级分类id" ) partitioned by(p_day string)
 stored as orc