create external table if not exists ods.ods_timely_trans_tasks (
    task_id bigint comment "线路任务ID" ,
    task_name string comment "线路任务" ,
    wid bigint comment "仓ID" ,
    cuid bigint comment "所属用户ID" ,
    type int comment "司机类型" ,
    dprice bigint comment "司机竞价" ,
    dcar_id bigint comment "司机车型ID" ,
    dcar_num string comment "司机车牌号" ,
    did bigint comment "司机ID" ,
    config string comment "时效配置" ,
    status int comment "状态" ,
    start_time double comment "开启时间" ,
    close_time double comment "关闭时间" ,
    out_time string comment "出仓时间" ,
    complete_time string comment "完成时间" ,
    create_time double comment "创建时间" ,
    update_time double comment "修改时间" ,
    config_type int comment "配置类型" )
 stored as orc