create external table if not exists ods.ods_customer_welfare_event (
    `id` bigint comment "客户福利事件ID" ,
    `customer_id` bigint comment "客户ID" ,
    `driver_id` bigint comment "司机ID" ,
    `adc_id` bigint comment "客户管理区" ,
    `city` string comment "司机所属城市" ,
    `district` string comment "司机所属区县" ,
    `reason` string comment "发放原因" ,
    `money` bigint comment "发放金额,单位是分" ,
    `tax` bigint comment "发放金额对应的税,单位是分" ,
    `operator_id` bigint comment "操作人员ID" ,
    `operator_nick` string comment "操作人员的名称" ,
    `from` bigint comment "数据产生的调用端信息" ,
    `sale_id` bigint comment "客户顾问ID" ,
    `updated_at` timestamp comment "" ,
    `created_at` timestamp comment "" ,
    `finance_pay_type` bigint comment "客户类型" ,
    `project_type` int comment "福利发放时客户的项目类型" ,
    `bu_leader_id` bigint comment "客户所属bu leader的id" )
 stored as orc