create external table if not exists ods.ods_trans_cargo_insurance_email_log (
    `id`  bigint comment "唯一id" ,
    `insurance_applicant_id`  bigint comment "投保人id，客户详情页“保险” 中设置的公司id" ,
    `customer_id`  bigint comment "客户id" ,
    `trans_event_id`  bigint comment "出车记录编号" ,
    `cargo_type`  string comment "货物类型" ,
    `cargo_number_min`  int comment "货物件数最小值，单位：个|件|箱|捆" ,
    `cargo_number_max`  int comment "货物件数最大值，单位：个|件|箱|捆" ,
    `car_num`  string comment "司机的车牌号码" ,
    `warehouse_address`  string comment "起始地，线路任务中所选仓库的仓库详细地址" ,
    `distribution_area`  string comment "目的地，线路任务中的配送区域描述" ,
    `check_in_time`  timestamp comment "起运时间，出车记录中的签到时间" ,
    `cprice_per_day`  bigint comment "运费，客户基础价格(不含税)，单位:分" ,
    `created_at`  timestamp comment "邮件发送时间" ,
    `is_for_test`  int comment "是否是测试数据，1代表哥谭市测试数据，0代表线上数据" ,
    `email`  string comment "发送邮件的邮箱地址，如果是多个邮箱用分号分割" ,
    `driver_id`  bigint comment "司机id" ,
    `insurance_type`  int comment "保险类型：中货值保险 或 高货值保险" ,
    `max_insurance`  bigint comment "最高赔偿限额，单位:分" ,
    `insurance_price`  bigint comment "给保险公司的保险费，单位:分" ,
    `status`  int comment "保险确认状态（调保险公司api的返回code）" ,
    `insurance_rate`  double comment "保险公司收取的保险比率 例如: 0.0070 (0.7%)" ,
    `updated_at`  timestamp comment "最近一次更新时间" ,
    `insure_way`  int comment "保险购买方式(100合约购买,200线路购买)" )
 stored as orc